package com.app.felixchidev.mypokegotool;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.app.felixchidev.mypokegotool.DBPokemon;

import com.app.felixchidev.mypokegotool.DBPokemonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBPokemonDaoConfig;

    private final DBPokemonDao dBPokemonDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBPokemonDaoConfig = daoConfigMap.get(DBPokemonDao.class).clone();
        dBPokemonDaoConfig.initIdentityScope(type);

        dBPokemonDao = new DBPokemonDao(dBPokemonDaoConfig, this);

        registerDao(DBPokemon.class, dBPokemonDao);
    }
    
    public void clear() {
        dBPokemonDaoConfig.getIdentityScope().clear();
    }

    public DBPokemonDao getDBPokemonDao() {
        return dBPokemonDao;
    }

}
